Apply patch for local downloads of patches to 8.x-6.0-rc4 tag

diff --git a/drush b/drush
--- a/drush
+++ b/drush
@@ -1,5 +1,4 @@
 #!/usr/bin/env sh
-# $Id$
 #
 # This script is a simple wrapper that will run Drush with the most appropriate
 # php executable it can find.
@@ -12,12 +11,14 @@ SELF_DIRNAME="`dirname -- "$0"`"
 SELF_PATH="`cd -P -- "$SELF_DIRNAME" && pwd -P`/`basename -- "$0"`"
 
 # Decide if we are running a Unix shell on Windows
-case "`uname -a`" in
-  CYGWIN*)
-    CYGWIN=1 ;;
-  MINGW*)
-    MINGW=1 ;;
-esac
+if [ `which uname` ]; then
+  case "`uname -a`" in
+    CYGWIN*)
+      CYGWIN=1 ;;
+    MINGW*)
+      MINGW=1 ;;
+  esac
+fi
 
 # Resolve symlinks - this is the equivalent of "readlink -f", but also works with non-standard OS X readlink.
 while [ -h "$SELF_PATH" ]; do
@@ -55,30 +56,34 @@ if [ -n "$DRUSH_PHP" ] ; then
   # Use the DRUSH_PHP environment variable if it is available.
   php="$DRUSH_PHP"
 else
-  # Default to using the php that we find on the PATH.
-  # We check for a command line (cli) version of php, and if found use that.
-  # Note that we need the full path to php here for Dreamhost, which behaves oddly.  See http://drupal.org/node/662926
-  php="$(which php-cli php 2>/dev/null | head -1)"
-
-  if [ ! -x "$php" ]; then
-    echo "ERROR: can't find php."; exit 1
-  fi
-
   # On MSYSGIT, we need to use "php", not the full path to php
   if [ -n "$MINGW" ] ; then
     php="php"
+  else
+    # Default to using the php that we find on the PATH.
+    # We check for a command line (cli) version of php, and if found use that.
+    # Note that we need the full path to php here for Dreamhost, which behaves oddly.  See http://drupal.org/node/662926
+    php="`which php-cli 2>/dev/null`"
+
+    if [ ! -x "$php" ]; then
+      php="`which php 2>/dev/null`"
+    fi
+
+    if [ ! -x "$php" ]; then
+      echo "ERROR: can't find php."; exit 1
+    fi
   fi
 fi
 
 # Check to see if the user has provided a php.ini file or drush.ini file in any conf dir
 # Last found wins, so search in reverse priority order
-for conf_dir in "`dirname "$SELF_PATH"`" /etc/drush $HOME/.drush ; do
-  if [ ! -d $conf_dir ] ; then
+for conf_dir in "`dirname "$SELF_PATH"`" /etc/drush "$HOME/.drush" ; do
+  if [ ! -d "$conf_dir" ] ; then
     continue
   fi
   # Handle paths that don't start with a drive letter on MinGW shell. Equivalent to cygpath on Cygwin.
   if [ -n "$MINGW" ] ; then
-    conf_dir=`sh -c "cd $conf_dir; pwd -W"`
+    conf_dir=`sh -c "cd \"$conf_dir\"; pwd -W"`
   fi
   if [ -f "$conf_dir/php.ini" ] ; then
     drush_php_ini="$conf_dir/php.ini"
@@ -114,13 +119,11 @@ if [ -n "$PHP_OPTIONS" ] ; then
   php_options="$php_options $PHP_OPTIONS"
 fi
 
-php_prohibited_options="-d magic_quotes_gpc=0 -d magic_quotes_runtime=0 -d magic_quotes_sybase=0"
+# Always disable magic_quotes_gpc and friends
+php_options="$php_options -d magic_quotes_gpc=Off -d magic_quotes_runtime=Off -d magic_quotes_sybase=Off"
 
-# Pass in the path to php so that drush knows which one
-# to use if it re-launches itself to run subcommands.  We
-# will also pass php options if any are defined.
-if [ -z "$php_options" ] ; then
-  exec "$php" $php_options $php_prohibited_options "$SCRIPT_PATH" --php="$php" "$@"
-else
-  exec "$php" $php_options $php_prohibited_options "$SCRIPT_PATH" --php="$php" --php-options="$php_options" "$@"
-fi
+# Pass in the path to php so that drush knows which one to use if it
+# re-launches itself to run subcommands.  We will also pass in the php options.
+# Important note: Any options added here must be removed  when Drush processes
+# a #! (shebang) script.  @see drush_adjust_args_if_shebang_script()
+exec "$php" $php_options "$SCRIPT_PATH" --php="$php" --php-options="$php_options" "$@"
